#!/bin/bash


INSTALL_DIR=~/.local/bin/
INSTALL_PATH="${INSTALL_DIR}gdvm"


case $1 in
	'--force')
		force=1;;
esac


LEGACY_COMPLETION=/usr/share/bash-completion/completions/gdvm
LEGACY_ICON=/usr/share/share/pixmaps/godot.png

if [ ! $force ]; then
	if [ -e $LEGACY_COMPLETION ]; then
		echo "Deleting ${LEGACY_COMPLETION} from a previous installation"
		sudo rm "$LEGACY_COMPLETION"
	fi

	if [ -e $LEGACY_ICON ]; then
		echo "Deleting ${LEGACY_ICON} from a previous installation"
		sudo rm "$LEGACY_ICON"
	fi
fi



# TODO: add ~/.local/bin to path if it's not in it
mkdir -p $INSTALL_DIR

# When autoupgrading, gdvm bin might still be busy, let's wait for gdvm to be done
sleep 0.5
echo
echo -n "Installing gdvm"
while lsof ${INSTALL_PATH} 1>/dev/null; do
	echo -n "."
	sleep 0.5
done
echo -ne "\n"

cp dist/gdvm $INSTALL_DIR

mkdir -p ~/.local/share/bash-completion/completions
cp gdvm.completion ~/.local/share/bash-completion/completions/gdvm

cp godot.png ~/.local/share/icons/
rm -r ~/.cache/gdvm 2> /dev/null || true

echo Installed gdvm to $INSTALL_DIR

gdvm sync
echo 'Done'
