#!/bin/bash

LAST_VERSION=$(git describe --tags --abbrev=0 $(git rev-list --tags --max-count=1))


MAJOR=$(echo ${LAST_VERSION:1} | cut -d "." -f 1)
MINOR=$(echo $LAST_VERSION | cut -d "." -f 2)
PATCH=$(echo $LAST_VERSION | cut -d "." -f 3)

case $1 in
	major)
		MAJOR=$(($MAJOR+1))
		MINOR=0
		PATCH=0
		;;
	minor)
		MINOR=$(($MINOR+1))
		PATCH=0
		;;
	patch)
		PATCH=$(($PATCH+1))
		;;
	*)
		exit 1
		;;
esac


VERSION=v${MAJOR}.${MINOR}.${PATCH}


read -p "Bump version $LAST_VERSION -> $VERSION? [y/N]: " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 0


MSG="bump: gdvm version $LAST_VERSION -> $VERSION"


git commit --allow-empty -m $MSG
git tag $VERSION
git push
git push origin $VERSION
