#!/usr/bin/env python3

import sys
import os
import subprocess as sp
import argparse

from os.path import basename, splitext, expanduser
from collections import namedtuple


INSTALL_PATH = '/usr/bin/godot'
SAVE_DIR = expanduser('~/.godot/')

os.makedirs(SAVE_DIR,exist_ok=True)



Choice = namedtuple('Choice', ['id','version','path'])


def extract_archive(file: str) -> str:
    """Extracts Godot archive to /tmp and return extracted file path"""
    sp.run(['unzip', file, '-d', '/tmp'])
    return '/tmp/' + basename(splitext(file)[0])


def add_archive(godot_file: str) -> str:
    """Add Godot app to the managed versions

    If the godot_file is a zip archive downloaded from Godot website,
    it is extracted first
    """
    # extract the zip archive if necessary
    if godot_file.endswith('.zip'):
        godot_file = extract_archive(godot_file)

    # make Godot executable
    sp.run(['chmod', '+x', godot_file])

    # add to the list of managed versions
    print(f'Saving a copy to {SAVE_DIR}{basename(godot_file)}')
    sp.run(['mv', godot_file, SAVE_DIR])
    return os.path.join(SAVE_DIR,basename(godot_file))


def install(godot_file: str):
    """Make godot_file the system Godot (from CLI and desktop)"""
    sp.run(['sudo', 'cp', godot_file, INSTALL_PATH])


def get_current_version() -> str:
    return get_version('godot')


def get_version(app_path: str) -> str:
    # check=True to check for exit error
    return sp.run([app_path, '--version'], check=False, stdout=sp.PIPE).stdout\
             .decode('utf-8')\
             .strip()


def managed_apps() -> list[str]:
    """Return paths of managed Godot apps"""
    return [os.path.join(SAVE_DIR,app) for app in os.listdir(SAVE_DIR)]


def versions() -> list[str]:
    """Return list of managed Godot versions"""
    return [get_version(app) for app in managed_apps()]


def selection_display(version: str) -> str:
    if version == get_current_version():
        return '-> '
    else:
        return '   '


def display_version_choice() -> list[Choice]:
    """Display a list of managed Godot versions with an associated number

    Return a Choice(id,version,app_path) named tuple
    """
    choices = [Choice(i, get_version(app), app)
               for i, app in enumerate(managed_apps())]

    to_display = [f'{selection_display(choice.version)}{choice.id}:\t{choice.version}'
                  for choice in choices]

    print('\n'.join(to_display))
    return choices


def pick_version() -> tuple:
    """Pick a Godot version from the list of managed versions

    Return the path to the corresponding Godot binary and the chosen version
    """
    # print versions with an associated number
    choices = display_version_choice()

    # ask which number to use
    try:
        usr_input = input('Enter the choosen number: ')
    except KeyboardInterrupt:
        print() # print on new line
        exit()

    try:
        chosen_number = int(usr_input)
    except ValueError:
        print('Incorrect input')
        abort()

    if not 0 <= chosen_number < len(choices):
        print('Incorrect number')
        abort()

    # return the chosen Godot version and its corresponding app path
    chosen_app = choices[chosen_number].path
    chosen_version = choices[chosen_number].version
    return chosen_app, chosen_version


def display_versions():
    """List existing Godot applications"""
    to_display = [f'{selection_display(version)}{version}'
                  for version in versions()]

    print('\n'.join(to_display))

def abort():
    print('Aborting...')
    exit()



# Instantiate the parser
parser = argparse.ArgumentParser(description='Install Godot system wise and manage versions')

# Make arguments mutually exclusive
exclusive_group = parser.add_mutually_exclusive_group()

# Install archive file
exclusive_group.add_argument('-i', '--install', metavar=('ARCHIVE'),
                    help='install Godot system wise from binary or zip archive')

# Change Godot version
exclusive_group.add_argument('-u', '--use', action='store_true',
                    help='pick the Godot version to use system wise')

# Add archive file without installing
exclusive_group.add_argument('-a', '--add', metavar=('ARCHIVE'),
                    help='add managed version from binary or zip archive without installing')

# Delete Godot version
exclusive_group.add_argument('-d', '--delete', action='store_true',
                             help='delete Godot version (remain installed system wise if currently in use)')

# Optional listing of available Godot version
exclusive_group.add_argument('-l', '--list', action='store_true',
                    help=f'list available Godot versions')

# Launch Godot from a list of available versions
exclusive_group.add_argument('-s', '--start', action='store_true',
                    help='launch Godot from the list of available versions')

# Parse arguments
args = parser.parse_args()

# Display help message when no args are passed.
if len(sys.argv)==1:
    parser.print_help()
    exit()




if args.list:
    display_versions()


if args.start:
    chosen_app, chosen_version = pick_version()
    print(f'Launching {chosen_version}')
    p = sp.Popen(chosen_app, stdin=sp.DEVNULL, stdout=sp.DEVNULL, stderr=sp.DEVNULL)


if args.use:
    chosen_app, chosen_version = pick_version()
    install(chosen_app)
    print(f'Using {chosen_version}')
    

if args.add:
    add_archive(args.add)


if args.delete:
    chosen_app, chosen_version = pick_version()
    match input(f'Are you sure you want to delete {chosen_version}? [y/N]: '):
        case 'y':
            os.remove(chosen_app)
            print(f'Deleted {chosen_version}')
        case other:
            abort()


if args.install:
    godot_file = add_archive(args.install)

    print(f'Installing to {INSTALL_PATH}')
    install(godot_file)
