#!/usr/bin/env python3

import sys
import subprocess
from os.path import basename, splitext, expanduser
from os import makedirs


assert(len(sys.argv)==2)

godot_file = sys.argv[1]

if godot_file.endswith('.zip'):
    subprocess.run(['unzip', godot_file, '-d', '/tmp'])
    godot_file = '/tmp/' + basename(splitext(godot_file)[0])

dest = '/usr/bin/godot'
save_dir = expanduser('~/.godot/')

makedirs(save_dir,exist_ok=True)


print(f'Installing to {dest}')
subprocess.run(['chmod', '+x', godot_file])
subprocess.run(['sudo', 'cp', godot_file, dest])
print(f'Saving a copy to {save_dir}{basename(godot_file)}')
subprocess.run(['mv', godot_file, save_dir])

