#!/usr/bin/env python3

import sys
import subprocess
from os.path import basename, splitext, expanduser
from os import makedirs

INSTALL_DIR = '/usr/bin/godot'
SAVE_DIR = expanduser('~/.godot/')

makedirs(SAVE_DIR,exist_ok=True)


def extract_archive(file: str) -> str:
    """ Extracts Godot archive to /tmp and return extracted file path"""
    subprocess.run(['unzip', file, '-d', '/tmp'])
    return '/tmp/' + basename(splitext(file)[0])




assert(len(sys.argv)==2)

godot_archive = sys.argv[1]

if godot_archive.endswith('.zip'):
    godot_file = extract_archive(godot_archive)


print(f'Installing to {INSTALL_DIR}')
subprocess.run(['chmod', '+x', godot_file])
subprocess.run(['sudo', 'cp', godot_file, INSTALL_DIR])


print(f'Saving a copy to {SAVE_DIR}{basename(godot_file)}')
subprocess.run(['mv', godot_file, SAVE_DIR])
