#!/usr/bin/env python3

import cli
from manager import AppManager
from helpers import abort




# Parse arguments
args = cli.parse_args()

# Display help message when no args are passed.
if not cli.has_arguments():
    cli.print_help()
    exit()


app_manager = AppManager()


if args.list:
    cli.display_versions(app_manager)


if args.start:
    chosen_app = cli.pick_version(app_manager)
    chosen_app.run()


if args.start_local:
    app_manager.run_project_version()


if args.use:
    chosen_app = cli.pick_version(app_manager)
    app_manager.install(chosen_app)


if args.use_local:
    chosen_app = cli.pick_version(app_manager)
    app_manager.install(chosen_app, project=True)


if args.add:
    app_manager.add(args.add)


if args.delete:
    chosen_app = cli.pick_version(app_manager)
    match input(f'Are you sure you want to delete {chosen_app.version}? [y/N]: '):
        case 'y':
            app_manager.remove(chosen_app)
        case other:
            abort()


if args.install:
    app_manager.install(args.install)
