[dependency-groups]
dev = [
    "altgraph>=0.17.4",
    "argcomplete>=3.6.2",
    "beautifulsoup4>=4.14.2",
    "bs4>=0.0.2",
    "certifi>=2025.8.3",
    "charset-normalizer>=3.4.3",
    "colorama>=0.4.6",
    "greenlet>=3.2.4",
    "idna>=3.10",
    "iniconfig>=2.1.0",
    "lxml>=6.0.2",
    "msgpack>=1.1.1",
    "packaging>=25.0",
    "pluggy>=1.6.0",
    "pyinstaller>=6.16.0",
    "pyinstaller-hooks-contrib>=2025.9",
    "pytest>=8.4.2",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "soupsieve>=2.8",
    "urllib3>=2.5.0",
    "wget>=3.2",
]
